# Generated by Django 5.2.13 on 2026-04-08 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_groups_grou_name_0806de_idx_and_more'),
        ('posts', '0002_alter_post_unique_together_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='posts_post_user_id_b93466_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', '-created_at'], name='posts_post_group_i_7a9c41_idx'),
        ),
    ]
