# Generated by Django 5.2.13 on 2026-04-08 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='groups_grou_name_0806de_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['slug'], name='groups_grou_slug_246a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-created_at'], name='groups_grou_created_30fc73_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'user'], name='groups_grou_group_i_07d300_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['-joined_at'], name='groups_grou_joined__0f2dd0_idx'),
        ),
    ]
